/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LowonganKerjaControllers;
import interfaces.LowonganKerjaInterface;
import controllers.UserControllers;
import interfaces.UserInterface;
import daos.DAOInterface;
import daos.GeneralDAO;
import entities.LowonganPekerjaan;
import entities.Pengalaman;
import entities.Users;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
import tools.getDataLogin;
import tools.getLoginData;

/**
 *
 * @author Nitani
 */
public class LowonganKerjaViews extends javax.swing.JInternalFrame {

    private JButton buttons;
    private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    private getLoginData data = new getLoginData(sessionFactory);
    private getDataLogin dataLogin = new getDataLogin();
    private LowonganKerjaInterface lki = new LowonganKerjaControllers(sessionFactory);

    /**
     * Creates new form LowonganKerjaViews
     */
    public LowonganKerjaViews() {
        initComponents();
        bindingTable(lki.search(""));
        lblUsersId.setText(String.valueOf(dataLogin.getUsersId()));
        btnUpdate.setEnabled(false);
        bindingTable(lki.getAllData(new LowonganPekerjaan(), ""));
    }

    public void clearText() {
        txtAreaJudul.setText("");
        txtAreaDeskripsi.setText("");
        txtAreaRequirement.setText("");
        btnTambah.setEnabled(true);

    }

    public void bindingTable(List<Object> lowongan) {
        Object[] header = {"No", "Judul Lowongan", "Deskripsi", "Requirements", "tanggal mulai", "tanggal selesai"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        tblLoker.setModel(model);

        int no = 1;
        try {
            for (Object low : lowongan) {
                LowonganPekerjaan emp = (LowonganPekerjaan) low;
                String isi = String.valueOf(no);
//                String isi1 = String.valueOf(data.getTotal(new LowonganPekerjaan()));
                String isi2 = emp.getJudul();
                String isi3 = emp.getDeskripsi();
                String isi4 = emp.getRequirements();
                String isi5 = String.valueOf(emp.getTanggalMulai());
                String isi6 = String.valueOf(emp.getTanggalSelesai());

                String kolom[] = {isi, isi2, isi3, isi4, isi5, isi6};
                model.addRow(kolom);
                no++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        txtAreaJudul = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDeskripsi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaRequirement = new javax.swing.JTextArea();
        email = new javax.swing.JLabel();
        dateMulai = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        dateSelesai = new org.jdesktop.swingx.JXDatePicker();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoker = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        lblUsersId = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Admin input lowongan");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Input Lowongan"));

        username.setText("Judul Lowongan");

        jLabel1.setText("Deskripsi Pekerjaan");

        role.setText("Requirement");

        txtAreaDeskripsi.setColumns(20);
        txtAreaDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtAreaDeskripsi);

        txtAreaRequirement.setColumns(20);
        txtAreaRequirement.setRows(5);
        jScrollPane3.setViewportView(txtAreaRequirement);

        email.setText("Tanggal mulai lowongan");

        jLabel2.setText("Tanggal selesei lowongan");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(username)
                        .addGap(43, 43, 43)
                        .addComponent(txtAreaJudul))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(role)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(jLabel2))
                        .addGap(18, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(txtAreaJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(role))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email)
                    .addComponent(dateMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dateSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnClear))
        );

        tblLoker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Judul Lowongan", "Deskripsi", "Requirements"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLokerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoker);

        jLabel3.setText("Search");

        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });

        lblUsersId.setText("userId");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsersId)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsersId)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        DateFormat format = new SimpleDateFormat("MM/dd/yyyy");
        Date tglMulai = dateMulai.getDate();
        Date tglSelesai = dateSelesai.getDate();
        String tanggalMulai = format.format(tglMulai);
        String tanggalSelesai = format.format(tglSelesai);
        String judul = txtAreaJudul.getText();
        String deskripsi = txtAreaDeskripsi.getText();
        String requirements = txtAreaRequirement.getText();

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Data akan di tambah?",
                "Insert Data", dialogButton);
        if (dialogResult == 0) {
            if (!judul.equals("") && !deskripsi.equals("") && !requirements.equals("") && !tanggalMulai.isEmpty() && !tanggalSelesai.isEmpty()) {
                if (lki.insert(String.valueOf(data.getTotal(new LowonganPekerjaan()).size() + 1), judul, deskripsi, requirements,
                        tanggalMulai, tanggalSelesai, String.valueOf(dataLogin.getUsersId()))) {
                    JOptionPane.showMessageDialog(null, "Insert berhasil");
                    bindingTable(lki.getAllData(new LowonganPekerjaan(), ""));
                } else {
                    JOptionPane.showMessageDialog(null, "insert gagal!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "form tidak boleh kosong!", "Message Alert",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        DateFormat format = new SimpleDateFormat("MM/dd/yyyy");
        String tglM = dateMulai.toString();
        tglM = tglM.substring(0, 10);
        String tglS = dateSelesai.toString();
        tglS = tglS.substring(0, 10);
        Date tglMulai = dateMulai.getDate();
        Date tglSelesai = dateSelesai.getDate();
        String tanggalMulai = format.format(tglMulai);
        String tanggalSelesai = format.format(tglSelesai);
        String judul = txtAreaJudul.getText();
        String deskripsi = txtAreaDeskripsi.getText();
        String requirements = txtAreaRequirement.getText();

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Data akan di ubah?",
                "Update Data", dialogButton);
        if (dialogResult == 0) {
            if (!judul.equals("") && !deskripsi.equals("") && !requirements.equals("") && !tanggalMulai.isEmpty()) {
                if (lki.insert(String.valueOf(data.getTotal(new LowonganPekerjaan())), judul, deskripsi, requirements,
                        tanggalMulai, tanggalSelesai, String.valueOf(dataLogin.getUsersId()))) {
                    JOptionPane.showMessageDialog(null, "Update berhasil");
                    bindingTable(lki.getAllData(new LowonganPekerjaan(), ""));
                } else {
                    JOptionPane.showMessageDialog(null, "Update gagal!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "form tidak boleh kosong!", "Message Alert",
                        JOptionPane.WARNING_MESSAGE);
            }
            clearText();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
        bindingTable(lki.search(searchTxt.getText()));
    }//GEN-LAST:event_searchTxtKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here
        clearText();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblLokerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLokerMouseClicked
        // TODO add your handling code here:
        btnUpdate.setEnabled(true);
        btnTambah.setEnabled(false);

        
        
        int i = tblLoker.getSelectedRow();
        TableModel model = tblLoker.getModel();
        txtAreaJudul.setText(model.getValueAt(i, 1).toString());
        txtAreaDeskripsi.setText(model.getValueAt(i, 2).toString());
        txtAreaRequirement.setText(model.getValueAt(i, 3).toString());
//        try {
//            String getTglMulai = tblLoker.getValueAt(i, 4).toString();
//            Date tglMulai = new SimpleDateFormat("MM/dd/yyyy").parse(getTglMulai);   
//        
//            dateMulai.setDate(tglMulai);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        try {
//            String getTglSelesai = tblLoker.getValueAt(i, 5).toString();
//            Date tglSelesai = new SimpleDateFormat("MM/dd/yyyy").parse(getTglSelesai);
//            dateSelesai.setDate(tglSelesai);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }


    }//GEN-LAST:event_tblLokerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private org.jdesktop.swingx.JXDatePicker dateMulai;
    private org.jdesktop.swingx.JXDatePicker dateSelesai;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUsersId;
    private java.awt.Panel panel1;
    private javax.swing.JLabel role;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable tblLoker;
    private javax.swing.JTextArea txtAreaDeskripsi;
    private javax.swing.JTextField txtAreaJudul;
    private javax.swing.JTextArea txtAreaRequirement;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
