/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LowonganKerjaControllers;
import interfaces.LowonganKerjaInterface;
import controllers.UserControllers;
import interfaces.UserInterface;
import controllers.UserProfileControllers;
import interfaces.UserProfileInterface;
import daos.DAOInterface;
import daos.GeneralDAO;
import entities.Bahasa;
import entities.LowonganPekerjaan;
import entities.Pencapaian;
import entities.Pengalaman;
import entities.Proyek;
import entities.RiwayatPendidikan;
import entities.UserProfile;
import entities.Users;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
import tools.getDataLogin;
import tools.getLoginData;

/**
 *
 * @author Nitani
 */
public class MainFrame extends javax.swing.JFrame {

    private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    private DAOInterface daoi = new GeneralDAO(sessionFactory);
    private UserInterface ai = new UserControllers(sessionFactory);
    private getLoginData ld = new getLoginData();
    private getDataLogin dataLogin = new getDataLogin();
    private UserProfilesView upv = new UserProfilesView();
    private UserViews uv = new UserViews();
    private SertifikatViews sv = new SertifikatViews();
    private LoginViews lv = new LoginViews();
    private KeahlianViews kv = new KeahlianViews();
    private LowonganKerjaViews lkv = new LowonganKerjaViews();
    private BahasaViews bahasas =  new BahasaViews();
    private PencapaianViews pencapaian =  new PencapaianViews();
    private PengalamanViews pengalaman = new PengalamanViews();
    private ProyekViews pv = new ProyekViews();
    private PendidikanViews pendidikanViews = new PendidikanViews();
    private ManagerViews mv = new ManagerViews();
    private CVViews cv = new CVViews();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        namaUser.setText(dataLogin.getUsersName());
        if(ai.getIdProfile(dataLogin.getUsersId())){
            getUsersId();
            sertifikatItem.setVisible(true);
            keahlianItem.setVisible(true);
            bahasaItem.setVisible(true);
            pencapaianItem.setVisible(true);
            pendidikanItem.setVisible(true);
            pengalamanItem.setVisible(true);
            projectItem.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Isi profile terlebih dahulu");
            upv.show();
            dsktpMain.add(upv);
            sertifikatItem.setVisible(false);
            keahlianItem.setVisible(false);
            bahasaItem.setVisible(false);
            pencapaianItem.setVisible(false);
            pendidikanItem.setVisible(false);
            pengalamanItem.setVisible(false);
            projectItem.setVisible(false);
        }
        
        if (dataLogin.getRole() == 1) {
            jMenu6.setVisible(false);
            jMenu7.setVisible(false);
        } else if (dataLogin.getRole() == 2) {
            jMenu5.setVisible(false);
            jMenu7.setVisible(false);
        } else if (dataLogin.getRole() == 3) {
            jMenu6.setVisible(false);
            jMenu5.setVisible(false);
        }
    }

    public void profile() {

    }

    public void getUsersId() {
        DateFormat formats = new SimpleDateFormat("d MMMM yyyy", Locale.ENGLISH);
        UserProfile users = (UserProfile) ai.getById(dataLogin.getUsersId());
        dataLogin.setUserProfileId(users.getId());
        emailUser.setText(users.getUsersId().getEmail());
        umurUser.setText(String.valueOf(users.getUmur()));
        domisiliUser.setText(users.getAlamat());
        Date birth = users.getTanggalLahir();
        tanggalLahir.setText(formats.format(birth));
        noTelp.setText(String.valueOf(users.getNoTelepon()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        dsktpMain = new javax.swing.JDesktopPane();
        logoutBtn = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailUser = new javax.swing.JLabel();
        umurUser = new javax.swing.JLabel();
        domisiliUser = new javax.swing.JLabel();
        tanggalLahir = new javax.swing.JLabel();
        noTelp = new javax.swing.JLabel();
        namaUser1 = new javax.swing.JLabel();
        namaUser = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        gambar3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        editProfiles = new javax.swing.JMenuItem();
        sertifikatItem = new javax.swing.JMenuItem();
        lowonganItem = new javax.swing.JMenuItem();
        keahlianItem = new javax.swing.JMenuItem();
        bahasaItem = new javax.swing.JMenuItem();
        pencapaianItem = new javax.swing.JMenuItem();
        pengalamanItem = new javax.swing.JMenuItem();
        projectItem = new javax.swing.JMenuItem();
        pendidikanItem = new javax.swing.JMenuItem();
        cvItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        managerItem = new javax.swing.JMenuItem();
        cvUser = new javax.swing.JMenuItem();
        menuKeahlian = new javax.swing.JMenuItem();
        menuPendidiakn = new javax.swing.JMenuItem();
        reportKeahlian = new javax.swing.JMenuItem();
        rprtBhs = new javax.swing.JMenuItem();
        rprtApply = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Home");

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        dsktpMain.setLayer(logoutBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dsktpMainLayout = new javax.swing.GroupLayout(dsktpMain);
        dsktpMain.setLayout(dsktpMainLayout);
        dsktpMainLayout.setHorizontalGroup(
            dsktpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsktpMainLayout.createSequentialGroup()
                .addContainerGap(797, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        dsktpMainLayout.setVerticalGroup(
            dsktpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsktpMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        userPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Profil"));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel5.setText("Umur");

        jLabel6.setText("Alamat");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("No Telepon");

        emailUser.setText("Kosong");

        umurUser.setText("Kosong");

        domisiliUser.setText("Kosong");

        tanggalLahir.setText("Kosong");

        noTelp.setText("Kosong");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTelp)
                    .addComponent(tanggalLahir)
                    .addComponent(domisiliUser)
                    .addComponent(umurUser)
                    .addComponent(emailUser))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(emailUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(umurUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domisiliUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalLahir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noTelp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaUser1.setText("Selamat datang");

        namaUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        namaUser.setText("Nama");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambar3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambar3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(namaUser1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaUser1)
                    .addComponent(namaUser)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jMenuBar3.setBackground(new java.awt.Color(102, 153, 255));
        jMenuBar3.setToolTipText("");

        jMenu5.setText("User");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        editProfiles.setText("Edit Profil");
        editProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfilesActionPerformed(evt);
            }
        });
        jMenu5.add(editProfiles);

        sertifikatItem.setText("Sertifikat");
        sertifikatItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sertifikatItemActionPerformed(evt);
            }
        });
        jMenu5.add(sertifikatItem);

        lowonganItem.setText("Cari Lowongan");
        lowonganItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowonganItemActionPerformed(evt);
            }
        });
        jMenu5.add(lowonganItem);

        keahlianItem.setText("Keahlian");
        keahlianItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keahlianItemActionPerformed(evt);
            }
        });
        jMenu5.add(keahlianItem);

        bahasaItem.setText("Bahasa");
        bahasaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bahasaItemActionPerformed(evt);
            }
        });
        jMenu5.add(bahasaItem);

        pencapaianItem.setText("Pencapaian");
        pencapaianItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencapaianItemActionPerformed(evt);
            }
        });
        jMenu5.add(pencapaianItem);

        pengalamanItem.setText("Pengalaman");
        pengalamanItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengalamanItemActionPerformed(evt);
            }
        });
        jMenu5.add(pengalamanItem);

        projectItem.setText("Project");
        projectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectItemActionPerformed(evt);
            }
        });
        jMenu5.add(projectItem);

        pendidikanItem.setText("Pendidikan");
        pendidikanItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanItemActionPerformed(evt);
            }
        });
        jMenu5.add(pendidikanItem);

        cvItem.setText("CV");
        cvItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvItemActionPerformed(evt);
            }
        });
        jMenu5.add(cvItem);

        jMenuBar3.add(jMenu5);

        jMenu6.setText("Admin");

        jMenuItem1.setText("Admin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar3.add(jMenu6);

        jMenu7.setText("Manager");

        managerItem.setText("Manager");
        managerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerItemActionPerformed(evt);
            }
        });
        jMenu7.add(managerItem);

        cvUser.setText("CV User");
        cvUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvUserActionPerformed(evt);
            }
        });
        jMenu7.add(cvUser);

        menuKeahlian.setText("Report Lowongan Kerja");
        menuKeahlian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeahlianActionPerformed(evt);
            }
        });
        jMenu7.add(menuKeahlian);

        menuPendidiakn.setText("Report Pendidikan");
        menuPendidiakn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPendidiaknActionPerformed(evt);
            }
        });
        jMenu7.add(menuPendidiakn);

        reportKeahlian.setText("Report Pencapaian & Pengalaman");
        reportKeahlian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportKeahlianActionPerformed(evt);
            }
        });
        jMenu7.add(reportKeahlian);

        rprtBhs.setText("Report Bahasa & Sertifikat");
        rprtBhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprtBhsActionPerformed(evt);
            }
        });
        jMenu7.add(rprtBhs);

        rprtApply.setText("Report Apply");
        rprtApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprtApplyActionPerformed(evt);
            }
        });
        jMenu7.add(rprtApply);

        jMenuBar3.add(jMenu7);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsktpMain))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dsktpMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        lkv.show();
        dsktpMain.add(lkv);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void editProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfilesActionPerformed
        // TODO add your handling code here:
        if (editProfiles.getText() == "Edit Profil") {
            upv.show();
            dsktpMain.add(upv);
        } else {
            upv.show();
            dsktpMain.add(upv);
        }
    }//GEN-LAST:event_editProfilesActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Yakin ingin logout?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            lv.show();
            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void lowonganItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowonganItemActionPerformed
        // TODO add your handling code here:
        uv.show();
        dsktpMain.add(uv);
    }//GEN-LAST:event_lowonganItemActionPerformed

    private void sertifikatItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sertifikatItemActionPerformed
        // TODO add your handling code here:
        sv.show();
        dsktpMain.add(sv);
    }//GEN-LAST:event_sertifikatItemActionPerformed

    private void keahlianItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keahlianItemActionPerformed
        // TODO add your handling code here:
        kv.show();
        dsktpMain.add(kv);
    }//GEN-LAST:event_keahlianItemActionPerformed

    private void pencapaianItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencapaianItemActionPerformed
        // TODO add your handling code here:
        pencapaian.show();
        dsktpMain.add(pencapaian);
    }//GEN-LAST:event_pencapaianItemActionPerformed

    private void bahasaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bahasaItemActionPerformed
        // TODO add your handling code here:
        bahasas.show();
        dsktpMain.add(bahasas);
    }//GEN-LAST:event_bahasaItemActionPerformed

    private void pengalamanItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengalamanItemActionPerformed
        // TODO add your handling code here:
        pengalaman.show();
        dsktpMain.add(pengalaman);
    }//GEN-LAST:event_pengalamanItemActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        getUsersId();
    }//GEN-LAST:event_jPanel2MouseEntered

    private void projectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectItemActionPerformed
        // TODO add your handling code here:
        pv.show();
        dsktpMain.add(pv);
    }//GEN-LAST:event_projectItemActionPerformed

    private void pendidikanItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanItemActionPerformed
        // TODO add your handling code here:
        pendidikanViews.show();
        dsktpMain.add(pendidikanViews);
    }//GEN-LAST:event_pendidikanItemActionPerformed

    private void managerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerItemActionPerformed
        // TODO add your handling code here:
        mv.show();
        dsktpMain.add(mv);
    }//GEN-LAST:event_managerItemActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        if(ai.getIdProfile(dataLogin.getUsersId())){
            getUsersId();
            sertifikatItem.setVisible(true);
            keahlianItem.setVisible(true);
            bahasaItem.setVisible(true);
            pencapaianItem.setVisible(true);
            pendidikanItem.setVisible(true);
            pengalamanItem.setVisible(true);
            projectItem.setVisible(true);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void cvItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvItemActionPerformed
        // TODO add your handling code here:
        cv.show();
        dsktpMain.add(cv);
    }//GEN-LAST:event_cvItemActionPerformed

    private void menuKeahlianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeahlianActionPerformed
        // TODO add your handling code here:
        ReportForm rf = new ReportForm("report5");
        rf.show();
        dsktpMain.add(rf);
    }//GEN-LAST:event_menuKeahlianActionPerformed

    private void cvUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvUserActionPerformed
        // TODO add your handling code here:
        cv.show();
        dsktpMain.add(cv);
    }//GEN-LAST:event_cvUserActionPerformed

    private void menuPendidiaknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPendidiaknActionPerformed
        // TODO add your handling code here:
        ReportForm rf = new ReportForm("report4");
        rf.show();
        dsktpMain.add(rf);
        
    }//GEN-LAST:event_menuPendidiaknActionPerformed

    private void reportKeahlianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportKeahlianActionPerformed
        // TODO add your handling code here:
        ReportForm rf = new ReportForm("report3");
        rf.show();
        dsktpMain.add(rf);
        
    }//GEN-LAST:event_reportKeahlianActionPerformed

    private void rprtBhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprtBhsActionPerformed
        // TODO add your handling code here:
        ReportForm rf = new ReportForm("report2");
        rf.show();
        dsktpMain.add(rf);
        
    }//GEN-LAST:event_rprtBhsActionPerformed

    private void rprtApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprtApplyActionPerformed
        // TODO add your handling code here:
        ReportForm rf = new ReportForm("report6");
        rf.show();
        dsktpMain.add(rf);
        
    }//GEN-LAST:event_rprtApplyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImageIcon icon = new ImageIcon(filename);
        gambar3.setIcon(icon);
        Image image = icon.getImage().getScaledInstance(gambar3.getWidth(), gambar3.getHeight(), Image.SCALE_SMOOTH);
        gambar3.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bahasaItem;
    private javax.swing.JMenuItem cvItem;
    private javax.swing.JMenuItem cvUser;
    private javax.swing.JLabel domisiliUser;
    private javax.swing.JDesktopPane dsktpMain;
    private javax.swing.JMenuItem editProfiles;
    private javax.swing.JLabel emailUser;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel gambar1;
    private javax.swing.JLabel gambar2;
    private javax.swing.JLabel gambar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem keahlianItem;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JMenuItem lowonganItem;
    private javax.swing.JMenuItem managerItem;
    private javax.swing.JMenuItem menuKeahlian;
    private javax.swing.JMenuItem menuPendidiakn;
    private javax.swing.JLabel namaUser;
    private javax.swing.JLabel namaUser1;
    private javax.swing.JLabel noTelp;
    private javax.swing.JMenuItem pencapaianItem;
    private javax.swing.JMenuItem pendidikanItem;
    private javax.swing.JMenuItem pengalamanItem;
    private javax.swing.JMenuItem projectItem;
    private javax.swing.JMenuItem reportKeahlian;
    private javax.swing.JMenuItem rprtApply;
    private javax.swing.JMenuItem rprtBhs;
    private javax.swing.JMenuItem sertifikatItem;
    private javax.swing.JLabel tanggalLahir;
    private javax.swing.JLabel umurUser;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
