/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ApplyControllers;
import controllers.LowonganKerjaControllers;
import controllers.SertifikatControllers;
import entities.Apply;
import entities.LowonganPekerjaan;
import entities.Users;
import interfaces.ApplyInterface;
import interfaces.LowonganKerjaInterface;
import interfaces.SertifikatInterface;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
import tools.getDataLogin;
import tools.getLoginData;

/**
 *
 * @author Nitani
 */
public class ManagerViews extends javax.swing.JInternalFrame {

    private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    private SertifikatInterface si = new SertifikatControllers(sessionFactory);
    private getLoginData ld = new getLoginData(sessionFactory);
    private getDataLogin dl = new getDataLogin();
    private ApplyInterface ai = new ApplyControllers(sessionFactory);
    private CVViews cv = new CVViews();

    /**
     * Creates new form ApplyViews
     */
    public ManagerViews() {
        initComponents();
        bindingTable(ai.search(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        getIdTable = new javax.swing.JTable();
        lihatBtn = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Manager");

        getIdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kandidat", "Lowongan", "Admin", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        getIdTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getIdTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(getIdTable);

        lihatBtn.setText("Lihat");
        lihatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lihatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bindingTable(List<Object> apply) {
        Object[] header = {"No", "Kandidat", "Lowongan", "Admin", "Status"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        getIdTable.setModel(model);
        try {
            for (Object low : apply) {
                Apply app = (Apply) low;
                String kolom[] = {String.valueOf(app.getId()), String.valueOf(app.getUserId().getNama()), app.getLowonganId().getJudul(), app.getLowonganId().getUserId().getNama(), app.getStatus()};
                model.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! " + e.getMessage());
        }
    }
    private void getIdTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getIdTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getIdTableMouseClicked

    private void lihatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatBtnActionPerformed
        // TODO add your handling code here:
        int i = getIdTable.getSelectedRow();
        TableModel model = getIdTable.getModel();
        int a = ld.getUserId(model.getValueAt(i, 1).toString());
        dl.setCvId(a);
    }//GEN-LAST:event_lihatBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable getIdTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihatBtn;
    // End of variables declaration//GEN-END:variables
}
