/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ApplyControllers;
import controllers.LowonganKerjaControllers;
import controllers.SertifikatControllers;
import entities.Apply;
import entities.LowonganPekerjaan;
import interfaces.ApplyInterface;
import interfaces.LowonganKerjaInterface;
import interfaces.SertifikatInterface;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
import tools.getDataLogin;
import tools.getLoginData;

/**
 *
 * @author Nitani
 */
public class ManagerViews extends javax.swing.JInternalFrame {

    private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    private SertifikatInterface si = new SertifikatControllers(sessionFactory);
    private getLoginData ld = new getLoginData(sessionFactory);
    private getDataLogin dl = new getDataLogin();
    private ApplyInterface ai = new ApplyControllers(sessionFactory);
    

    /**
     * Creates new form ApplyViews
     */
    public ManagerViews() {
        initComponents();
        bindingTable(ai.search(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        getIdTable = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Manager");

        getIdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kandidat", "Lowongan", "Admin", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        getIdTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getIdTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(getIdTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bindingTable(List<Object> apply) {
        Object[] header = {"No", "Kandidat", "Lowongan", "Admin", "Status"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        getIdTable.setModel(model);
        try {
            for (Object low : apply) {
                Apply app = (Apply) low;
                String isi1 = String.valueOf(app.getId());
                String isi2 = app.getUserId().getNama();
                String isi3 = app.getLowonganId().getJudul();
                String isi4 = app.getLowonganId().getUserId().getNama();
                String isi5 = app.getStatus();

                String kolom[] = {isi1, isi2, isi3, isi4, isi5};
                model.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops! " + e.getMessage());
        }
    }
    private void getIdTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getIdTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getIdTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable getIdTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
